curators:
 - alexellis
 - Waterdrips
 - utsavanand2

features:
 - dco_check
 - comments
 - pr_description_required
 - release_notes
# - hacktoberfest

custom_messages:
  - name: slack
    value: |
           --
           Join Slack to connect with the community using the `#inlets` channel
           within the OpenFaaS Slack workspace.
           https://docs.openfaas.com/community

